# Generated by Django 4.2.5 on 2023-09-23 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=255)])),
                ('green', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=255)])),
                ('blue', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=255)])),
            ],
        ),
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color1', to='core.color')),
                ('color10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color10', to='core.color')),
                ('color2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color2', to='core.color')),
                ('color3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color3', to='core.color')),
                ('color4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color4', to='core.color')),
                ('color5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color5', to='core.color')),
                ('color6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color6', to='core.color')),
                ('color7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color7', to='core.color')),
                ('color8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color8', to='core.color')),
                ('color9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color9', to='core.color')),
            ],
        ),
        migrations.CreateModel(
            name='strip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_image', models.ImageField(upload_to='samples/')),
                ('strip_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colors')),
            ],
        ),
    ]
